#ifndef EXERCISE_III_COMMANDS_H
#define EXERCISE_III_COMMANDS_H

#define LOG_ON "LOG_ON"
#define GET_CLIENTS "GET_CLIENTS"
#define LOG_OFF "LOG_OFF"
#define GET_FILE_LIST "GET_FILE_LIST"
#define GET_FILE "GET_FILE"

#endif //EXERCISE_III_COMMANDS_H
